# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5b75e639b7df55bd11679ae8d74230ae25ceaa53e09f2f0a375a7aebcb10133559373be7161725071300d47dd62599ecf295cab79cb23d7759844859b0214a39

test:
  secret_key_base: f84780e641108bd308de318bab8fd90228a3341941241a6bd644558b04bce9370990daf7d32748efde55a4fea2d9a24a733e38b58cd8e969fe1178a32f6566b5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
